### ISSUE TITLE
Resubmit: Add bitcoincashwallet.org browser based wallet to list of browser wallet links

### ISSUE THREAD

**Issue by cashaccount** [bchinfo/bch.info#213] opened 2024-02-21 06:16 UTC
The wrong index.html file was uploaded previously by mistake. Will attempt https soon.

**Comment by merc1er** [comment] 2024-02-21 06:19
Duplicate of https://github.com/bchinfo/bch.info/issues/212

**Closed by merc1er** 2024-02-21 06:19 UTC
